### ISSUE TITLE
Some configuration files not found

### ISSUE THREAD

**Issue by john-alstru** [ria-ee/X-Road#13]
Hello,

There are some configuration files can't be found when running ./build_packages.sh script.
The errors are like the below,
`Cannot locate configuration source /etc/xroad/conf.d/common.ini`
`Cannot locate configuration source /etc/xroad/conf.d/proxy.ini`
`Cannot load addon configuration
java.nio.file.NoSuchFileException: /etc/xroad/conf.d/addons`
`Cannot load override configuration
java.nio.file.NoSuchFileException: /etc/xroad/conf.d`

I didn't find the /etc/xroad directory. Did I miss some steps?

Thanks.

**Comment by jhyoty** [comment]
I assume that you are getting those warnings at the "runproxytest" step, which runs the proxy test suite. When running the test suite, these warnings can be ignored.

**Comment by john-alstru** [comment]
Yes. The errors occurred at the ":proxy:runProxyTest".

Thank you.
