### ISSUE TITLE
A warning when building packages

### ISSUE THREAD

**Issue by john-alstru** [ria-ee/X-Road#18]
I have executed the build_packages script successfully, but I got a warning in the console.

```
warning: Bundler `path' components are not currently supported.
The `common-ui-0.0.1' component was not bundled.
Your application may fail to boot!
rm -f build/libs/center-service.war
```
I don't know if it matters.
Does it mean I didn't install the common-ui correctly?

Thanks.

**Comment by iluwatar** [comment]
Unfortunately I cannot reproduce that warning in [my local build](https://github.com/ria-ee/X-Road/files/857213/output.txt).
- Are you following the [build instructions](https://github.com/ria-ee/X-Road/blob/develop/src/BUILD.md)?
- Which branch are you building?

**Comment by iluwatar** [comment]
The CI build seems to produce this warning. Actually it occurs 3 times (center-service, center-ui, proxy-ui). Good news is that it doesn't affect the build. The produced packages work nevertheless.

**Comment by iluwatar** [comment]
I've raised an issue for the warbler project about this warning. Hopefully we get input how to resolve this.

**Comment by john-alstru** [comment]
Thank you very much.
