### ISSUE TITLE
Build part and install part

### ISSUE THREAD

**Issue by rock1103** [ria-ee/X-Road#19]
Hi:
the readme.md show that Build and install, If I want to install the whole xroad plat,do I need to do the first step of Build,or not do the build part,direct to the install part.

Build

See instructions in src/BUILD.md

Install

X-Road central servers, configuration proxies and security servers can be automatically installed with the Ansible scripts found in ansible subdirectory. See instructions in ansible/README.md

**Comment by iluwatar** [comment]
There are options depending on what you want to achieve.

A) If you want to join an existing ecosystem (Finnish Palveluväylä or Estonian X-Tee) with your own security server you should follow the nation specific instructions
B) If you want to create and deploy X-Road on your own servers (including the central infrastructure) you can either build the packages from the source code or use existing package repositories for installation
C) If you want to create a local X-Road development environment then I would recommend setting up a development machine that can run the X-Road servers in LXD containers

**Comment by rock1103** [comment]
now I complete the xroad deb package and install the xroad-confproxy_6.10.0-1.20170308072412git83d72c6_all.deb,but an issue occur:

john@www:~/xroad-deb$ sudo dpkg -i xroad-confproxy_6.10.0-1.20170308072412git83d72c6_all.deb 
[sudo] password for john: 
dpkg: considering removing xroad-proxy in favour of xroad-confproxy ...
dpkg: no, cannot proceed with removal of xroad-proxy (--auto-deconfigure will help):
 xroad-securityserver depends on xroad-proxy (>= 6.10.0)
  xroad-proxy is to be removed.

dpkg: regarding xroad-confproxy_6.10.0-1.20170308072412git83d72c6_all.deb containing xroad-confproxy:
 xroad-confproxy conflicts with xroad-proxy
  xroad-proxy (version 6.10.0-1.20170308072412git83d72c6) is present and installed.

dpkg: error processing archive xroad-confproxy_6.10.0-1.20170308072412git83d72c6_all.deb (--install):
 conflicting packages - not installing xroad-confproxy
Errors were encountered while processing:
 xroad-confproxy_6.10.0-1.20170308072412git83d72c6_all.deb

**Comment by iluwatar** [comment]
Configuration proxy cannot be installed on the same server as security server.
