### ISSUE TITLE
How can I reach the CS and SS config homepage?

### ISSUE THREAD

**Issue by huangsongyun** [ria-ee/X-Road#21]
Hello;
Some questions for you help.
I have  installed xroad By using LXD and it shows running.
See below
![oz_ug 2jgh zfrzpnt0 sdg](https://cloud.githubusercontent.com/assets/20059840/24576838/a750589c-16f5-11e7-9bd8-37e04add2924.png)
But I can't ping the ipv4 address  and how can I open the config homepage in browser?
the port and the application name?

**Comment by rock1103** [comment]
@iluwatar
 Hi, I have run the command of ansible-playbook  -i hosts/lxd_hosts_from_local.txt xroad_dev.yml successful,
how can I access the center server and security server.

**Comment by iluwatar** [comment]
Have you tried accessing https://ip-address:4000?

**Comment by rock1103** [comment]
Yes,I try it ,but how do I access the security server and center server in my host computer of brower. not in the virtual box, my host comput ip is 192.168.1.109, it can't ping the security server ip 10.29.35.54.should xld configure any info?

**Comment by VitaliStupin** [comment]
It would be much easier to just use browser inside your virtual machine. Just use ubuntu-desktop or if you currently have ubuntu-server install "Ubuntu desktop" using "sudo tasksel".

If you really need to use browser on your host machine then it would require some complicated SSH tunneling or routing to make that possible.

Xsd creates an internal "lxdbr0" interface with internal nerwork inside the virtual machine. And your host machine cannot directly use that.

**Comment by rock1103** [comment]
@VitaliStupin Hi, if host machine cannot directly use that, it is hard for a team to develop xroad provider and consumer interface to access xroad.

**Comment by Jevli** [comment]
@rock1103 You can forward ports from Virtual Machine to Host. If you are using VirtualBox, here is general guide: https://www.howtogeek.com/122641/how-to-forward-ports-to-a-virtual-machine-and-use-it-as-a-server/. 

There is also possibility use Vagrantfile to use that for also: 
https://github.com/ria-ee/X-Road/blob/develop/src/Vagrant.md

**Comment by zhtlee** [comment]
@huangsongyun  I am in Beijing , Have you ever met my question? the only opened issue
