### ISSUE TITLE
global configuration generate fail

### ISSUE THREAD

**Issue by rock1103** [ria-ee/X-Road#22]
hi:
now I access the center server,these are some issue:
global configuration generate fail:

![xroad](https://cloud.githubusercontent.com/assets/7257681/24848450/68efa5ca-1df9-11e7-8e59-6f835372f7d2.jpg)

thank you.

**Comment by VassilMarjunits** [comment]
https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#32-initializing-the-central-server

"3.2 Initializing the Central Server"

**Comment by rock1103** [comment]
yes,I have already done it,and I have used the command 'ansible-playbook  -i hosts/lxd_hosts_from_local.txt xroad_dev.yml' to install the center server,with the error :global configuration generate fail

**Comment by iluwatar** [comment]
The Ansible scripts install the software packages to the LXD containers but still you have to configure the servers manually. The error message looks like the internal and external configuration signing keys are missing.

**Comment by rock1103** [comment]
I have create the signing keys,but now have one issue:
global configuration generate fail
![1](https://cloud.githubusercontent.com/assets/7257681/24938042/4e4005d4-1f67-11e7-9c39-1e8dd1b42e47.jpg)
how to solve this problem?

**Comment by iluwatar** [comment]
Have you completed the configuration steps mentioned in the link @VassilMarjunits posted? What is the error message in `/var/log/xroad/jetty/jetty.log`?

**Comment by rock1103** [comment]
I have already configured  certification services and timestamping services,but still have the issue:
global configuration generate fail
/var/log/xroad/jetty/jetty.log is
![qq 20170413125515](https://cloud.githubusercontent.com/assets/7257681/24990989/518d6e6e-204a-11e7-8920-6afb16b45f69.jpg)

**Comment by iluwatar** [comment]
The log snippet does not show the root cause. Can you attach the whole log file?

**Comment by rock1103** [comment]
/managementservice - Failed to generate valid global configuration: Management services provider is not configured
how to configure Management services?

**Comment by iluwatar** [comment]
https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#42-configuring-the-management-service-provider
