### ISSUE TITLE
web page localized language

### ISSUE THREAD

**Issue by rock1103** [ria-ee/X-Road#23]
Hi:
Now the user management interface web page of security server and center server  is english language,
if I want to change the language with localized language, should I change these in database?what steps should I do?

**Comment by iluwatar** [comment]
At the moment the only supported language is English. The software has mechanisms to support multiple languages but you would have to translate and maintain it yourself.

**Comment by rock1103** [comment]
what's the mechanisms it is,do you have detail steps?
thank you.

**Comment by eramirez-sv** [comment]
You use the english language files to create create versions in your own language, your new files will be included in your packages after compilation. To list all the required files from the xroad source code folder you can do:
~# find . -name *_en.yml
./center-ui/config/locales/controllers_en.yml
./center-ui/config/locales/views_en.yml
./common-ui/config/locales/controllers_en.yml
./common-ui/config/locales/views_en.yml
./proxy-ui/config/locales/controllers_en.yml
./proxy-ui/config/locales/views_en.yml

Hope this helps,
