### ISSUE TITLE
How to get a trusted anchor file?

### ISSUE THREAD

**Issue by john-alstru** [ria-ee/X-Road#25]
I'm configuring the trusted anchors in the central server that needs to upload a trusted anchor file.

Where can I get a trusted anchor file? Or generate one to test?

Thank you.

**Comment by iluwatar** [comment]
Trusted anchors are used for trust federation between multiple X-Road instances (i.e. to join multiple X-Road systems together). If you want to do that, you can get the configuration anchor from central server or configuration proxy (if they are used).

**Comment by john-alstru** [comment]
Thanks.
