### ISSUE TITLE
Download URL doesn't work

### ISSUE THREAD

**Issue by john-alstru** [ria-ee/X-Road#26]
In the central server, I can download the anchor file in the internal configuration tab by clicking download button. But when I use the Download url like `http://xroad-lxd-cs/internalconf` from a browser, I got a 404 error.
```
404 Not Found

nginx
```

No error message in the nginx log file. But there something wrong in the jetty log,

```
Failed to generate global configuration: Management services provider is not configured
[qtp1468357786-40] INFO  /managementservice - Failed to remove new conf directory, message:
undefined method 'each_value' for nil:NilClass
[qtp1468357786-40] INFO  /managementservice - Failed to generate valid global configuration: Management services provider is not configured
```

**Comment by iluwatar** [comment]
The central server is not generating the global configuration. The reason is mentioned in the jetty.log: `Failed to generate valid global configuration: Management services provider is not configured`.

**Comment by john-alstru** [comment]
Thanks.
