### ISSUE TITLE
Problems with Use command sign on a file

### ISSUE THREAD

**Issue by huangsongyun** [ria-ee/X-Road#31]
![sign](https://cloud.githubusercontent.com/assets/20059840/25168042/9fb11b08-2514-11e7-9301-bad572a2f0c0.png)

follow the step in demo,i use the CSR generated by key:sign in security server.
but i can't get the Certificate details as below,need your help:

![mysign](https://cloud.githubusercontent.com/assets/20059840/25168070/bc669af2-2514-11e7-9fc6-61684316b06c.png)

**Comment by iluwatar** [comment]
How does the certificate request look like if you examine it with command `openssl req -in sign_csr_20170419_member_xroad-cs_COMPANY_001.der -text -noout -inform DER`?

**Comment by huangsongyun** [comment]
as below:
root@xroad-lxd-cp:~# openssl req -in sign_csr_20170419_member_xroad-cs_COMPANY_001.der -text -noout -inform DER
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: serialNumber=001, CN=alstru
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a1:95:d4:8c:79:c7:e8:cc:32:ff:6d:a1:ae:c7:
                    c3:56:e8:92:21:89:04:3d:b6:3b:91:00:65:a1:82:
                    ee:7e:86:b1:51:b2:6c:40:9f:5f:0f:dd:ed:dd:88:
                    5a:9e:61:5c:99:42:5e:85:8f:c3:bb:dc:31:c5:e3:
                    ad:f0:d6:c0:56:2a:74:83:88:e6:9f:0b:ed:c6:5c:
                    15:2e:4b:0d:6f:1d:8c:0a:f0:61:c3:61:84:b2:61:
                    32:12:93:04:05:54:ef:a2:1f:c2:8b:19:a1:19:d3:
                    73:db:15:a9:21:5e:0d:d4:b8:87:e6:c2:eb:43:4f:
                    75:2f:11:88:45:d3:6b:e6:cf:5b:c4:22:9c:fe:67:
                    af:ab:bc:18:c4:f8:8b:77:7a:c1:b8:33:11:f4:1d:
                    68:55:54:97:f1:f2:e6:2b:f1:a3:3d:0a:82:8c:1a:
                    81:54:29:a5:cb:2b:35:3e:45:d2:f2:2d:93:e0:3d:
                    46:de:a9:1d:7c:f1:a2:94:f9:63:82:ca:c3:bf:34:
                    38:ae:21:49:12:22:6e:4e:b1:cf:d9:78:fc:28:15:
                    50:04:bb:f6:9a:16:61:52:bc:15:97:25:04:11:ec:
                    8e:11:10:96:77:ef:ba:cc:d2:c7:1a:38:97:4e:87:
                    b9:7b:8f:a0:8e:2c:18:f2:64:69:46:f0:42:81:3e:
                    d5:c1
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00
    Signature Algorithm: sha256WithRSAEncryption
         83:53:ad:e9:75:88:82:5f:4e:06:d2:fd:0b:f2:d8:48:ac:3d:
         22:c5:28:4b:36:82:8b:91:98:29:db:e9:5c:16:81:87:d7:9e:
         50:b4:45:0a:94:d4:ed:db:65:f6:3e:c6:ec:50:0b:49:09:41:
         94:62:18:05:65:51:c0:ca:37:56:69:66:da:ab:7d:da:f2:f5:
         6e:7d:72:ef:a4:1d:59:da:6b:bc:45:4c:c7:ab:f8:67:7b:74:
         7e:e4:04:2f:c0:76:90:2b:da:fd:c2:d0:e6:14:9f:e3:e7:7e:
         a0:6a:9d:8e:ed:ce:87:c4:e9:5e:84:66:7c:1c:6b:84:8d:60:
         60:3d:4c:eb:a1:c2:f5:87:f2:09:e2:65:df:de:69:a2:cf:1d:
         2a:e7:12:ba:55:71:37:87:e7:0c:27:09:e4:da:50:3a:47:dd:
         46:4c:f7:8f:6e:43:1e:c5:08:b9:c3:69:ee:f0:4f:43:fe:2e:
         7b:78:4a:25:b8:0f:a9:60:b2:2a:3d:30:2a:c7:4f:bd:ee:ac:
         9a:8f:54:3f:7a:a1:ca:5b:da:cb:a8:48:ec:c4:f8:21:6e:3d:
         cc:0e:84:07:aa:b7:87:22:51:0d:9a:01:e2:4d:86:e0:60:93:
         45:c1:5b:31:47:e0:87:12:c3:03:b0:cc:4c:9f:d2:ce:ba:59:
         75:82:bf:57

**Comment by iluwatar** [comment]
The request doesn't have the country field. For me the subject line looks like `Subject: C=FI, O=Demo RH2/serialNumber=DEMO/demo-rh2.i.palveluvayla.com/DMO, CN=demo-rh2.i.palveluvayla.com`.

What version of X-Road are you using?

How did you configure the certification services on the central server?

**Comment by huangsongyun** [comment]
I install the last xroad with ansible and source code is new ,and the version is 6.9.
And I create the certs with step 6 in Test-CA with TSA and OCSP ,details in below url:
https://github.com/ria-ee/X-Road/blob/develop/ansible/TESTCA.md

Then generate the key and der according to the docs.
[UG-SS] Security Server User Guide
[UG-CS] Central Server User Guide

**Comment by huangsongyun** [comment]
my subject like this ,when i use key to generate the request:
![bb](https://cloud.githubusercontent.com/assets/20059840/25172482/cb614156-2523-11e7-810b-2af9236b30d3.png)

**Comment by iluwatar** [comment]
The dialog is supposed to look like 
![subject-distinguished-name](https://cloud.githubusercontent.com/assets/582346/25175215/9f2885c0-2502-11e7-9f97-95811e30ade4.png)

It looks different for you because the certification services on the central server have been configured differently. On the central server choose `Certification Services` and edit the `Approved Certification Service`. Choose `CA Settings` and set `Certificate Profile Info` to `ee.ria.xroad.common.certificateprofile.impl.FiVRKCertificateProfileInfoProvider`. 

After few minutes when the global configuration on the security server has updated you will see the new dialog when you create a certificate signing request and you should be able to generate a CSR that can be signed successfully with the test-CA.

**Comment by huangsongyun** [comment]
Thanks,yes,it works with your ProfileInfoProvider,but now there is another problem need your help.
When I am Generating a Certificate Signing Request for an Authentication Key,
![reg-ss](https://cloud.githubusercontent.com/assets/20059840/25211208/a8c7ee9a-25b6-11e7-88b6-c807174fe818.png)

It shows "Registration in progress" after clicking the register button in Security Server ,then I try to pass the registration request in Central Server,but,I can't find the valid button on the interface ,neither in the dialog opening with detail button.
![reg-ss](https://cloud.githubusercontent.com/assets/20059840/25211621/9832a3c0-25b8-11e7-98c3-240c6a8a1725.png)

So i try to add the access right found in 8.3 of central_server_user_guide,but it shows already added.
![reg-pri](https://cloud.githubusercontent.com/assets/20059840/25211548/49b2e2b4-25b8-11e7-9d43-8f2d4375b7a3.png)
![cs-user](https://cloud.githubusercontent.com/assets/20059840/25211561/5380f434-25b8-11e7-9105-b508dc25f3e6.png)

**Comment by iluwatar** [comment]
The authentication certificate has now been added to security server and you have made the registration request. The next step is to add the authentication certificate to the central server also.

1. On the central server open `Members` page
2. Select the member that owns the security server and click `Details`
3. Select `Owned Servers`
4. Click `Add`
5. Input the `Server Code` as you have defined on the security server
6. Upload the authentication certificate by clicking `Upload`

The management request can now be approved (i.e. it is no longer in `WAITING` state) on the `Management Requests` page. It takes a few minutes for the global configuration to propagate to the security servers but after a while the authentication certificate shows good/registered on the `Keys and Certificates` page.
