### ISSUE TITLE
Could not find addresses for service provider "SERVICE:testcenterserver/MEMCLASSTEST/member1/subtest/clientReg"

### ISSUE THREAD

**Issue by rock1103** [ria-ee/X-Road#33]
Hi:
![1](https://cloud.githubusercontent.com/assets/7257681/25269766/97a29bce-26b0-11e7-93ca-4dd7deeb0c28.jpg)
when I register the clients,an issue occur.
Failed to send registration request: Could not find addresses for service provider "SERVICE:testcenterserver/MEMCLASSTEST/member1/subtest/clientReg"
thank you.

**Comment by huangsongyun** [comment]
some similar questions need your help !
I register with the Management Services In Central Server like this:
![cs-reg](https://cloud.githubusercontent.com/assets/20059840/25320534/9113aa7e-28da-11e7-911a-16f02c72cbab.png)

Then I register the subsystem in Security Server ,a few minutes later it shows registered! but unregister button doesn't work.
![ss-reg](https://cloud.githubusercontent.com/assets/20059840/25320542/9c4de36e-28da-11e7-87bc-bd13f82119f6.png)

**Comment by huangsongyun** [comment]
@iluwatar

**Comment by iluwatar** [comment]
It seems that the management services need some more configuration. See this guide for instructions 
[PVAYLADEV-CentralServer6.9.0configuration-250417-1515-27416.pdf](https://github.com/ria-ee/X-Road/files/957251/PVAYLADEV-CentralServer6.9.0configuration-250417-1515-27416.pdf).
