### ISSUE TITLE
Failed to send registration request: Request is not allowed: SERVICE:testcenterserver/GOV/member2/subtest2/clientReg

### ISSUE THREAD

**Issue by rock1103** [ria-ee/X-Road#34]
Hi:
the manage service is
![1](https://cloud.githubusercontent.com/assets/7257681/25323813/8a16381c-28f4-11e7-832d-bee12a47e4c4.jpg)

![2](https://cloud.githubusercontent.com/assets/7257681/25323818/912efba2-28f4-11e7-96e2-bbd208a60065.jpg)
when I register the client of membertest4
![3](https://cloud.githubusercontent.com/assets/7257681/25323821/99617e8a-28f4-11e7-933c-79a8b5701bb0.jpg)
Failed to send registration request: Request is not allowed: SERVICE:testcenterserver/GOV/member2/subtest2/clientReg

**Comment by iluwatar** [comment]
See https://github.com/ria-ee/X-Road/issues/33 for guide how to configure management services.
