### ISSUE TITLE
multiservice SOAP adapter/gateway

### ISSUE THREAD

**Issue by eramirez-sv** [ria-ee/X-Road#35]
We really like the rest-gateway because  it allows developers to build their services without having to add xroad's mandatory headers for each service. 
I know the xroad-adapter developed in Java is fairly simple to tweak but it requires to do it once for each  SOAP service behind my security server. Is there a multi-service soap adapter/gateway?  
Thanks in advance for you help.

**Comment by iluwatar** [comment]
@eramirez-sv the issue is not directly related to X-Road code repository. Please open feature request to https://github.com/vrk-kpa/REST-adapter-service.

**Comment by iluwatar** [comment]
Possibly duplicate of https://github.com/educloudalliance/xroad-rest-gateway/issues/27
