### ISSUE TITLE
quickly develop wsdl

### ISSUE THREAD

**Issue by rock1103** [ria-ee/X-Road#37]
Hi:
now I develop xroad consumer and product interface by
https://github.com/petkivim/x-road-adapter-example
how to create example.xroad-6.4.wsdl quickly, now I create it by hand, and it is so tedious.
do you have some tool to create  the wsdl auto.

thank you

**Comment by iluwatar** [comment]
@rock1103 it is described in https://github.com/petkivim/x-road-adapter-example/blob/master/README.md where you can download the wsdl once the service is running. The question is not directly related to X-Road code repository so I'm closing it.
