### ISSUE TITLE
Failed to send registration request: Security server has no valid authentication certificate

### ISSUE THREAD

**Issue by john-alstru** [ria-ee/X-Road#38]
Hello,

I met an error when registering a client.

![1](https://cloud.githubusercontent.com/assets/12060643/25653214/86692770-301e-11e7-9967-0e9a8056e13b.png)

But I have the authenticate certificate registered.

![2](https://cloud.githubusercontent.com/assets/12060643/25653249/a8b8dcda-301e-11e7-833e-db7bfbdcaaa6.png)

Thanks.

**Comment by iluwatar** [comment]
It seems that the security server doesn't have valid ocsp responses (state "unknown").
- Verify that authentication service is configured on the central server
- Verify that the security server can access the ocsp responder port
- Verify that the xroad-signer is running on the security server and no errors are shown in the log `/var/log/xroad/signer.log`

**Comment by john-alstru** [comment]
yes, I just solved the problem. it's because the ca service can't be started.

Thank you.
