### ISSUE TITLE
Changing IP configuration for Central and Security Server

### ISSUE THREAD

**Issue by algmomizz** [ria-ee/X-Road#39]
Hi,
      Up until now we've been able to run x-road central and security server instances with internal IP addresses. Now we're going to need to test a security-to-security server connection  (as well as cs for ca and tsa services) with an external entity. The goal is to be able to exchange data between both ss servers, so we need to expose our current x-road instances. How would we go about doing this changes?. If there's anything useful in the current doc any pointers would be greatly appreciated it. Thanks

Regards

**Comment by iluwatar** [comment]
There is no easy way to expose the servers once they have been registered with internal IP addresses. Basically you should register the servers with public addresses if you want them to be publicly available. If reinstallation is not possible I would look into VPN solutions or maybe something like [sshuttle](https://github.com/apenwarr/sshuttle) might work.

**Comment by iluwatar** [comment]
1. For central server uninstallation

```
#!/bin/sh
  
set -x
  
sudo apt-get purge xroad-common
sudo apt-get autoremove
sudo rm -rf /etc/xroad
sudo rm -rf /usr/share/xroad
sudo rm -rf /var/lib/xroad
sudo rm -rf /var/log/xroad
sudo rm -rf /var/tmp/xroad
sudo apt-get purge nginx
sudo -u postgres dropdb centerui_production
sudo -u postgres psql -c "drop user centerui"
sudo apt-get purge postgresql
```

For security server uninstallation (Ubuntu).

```
#!/bin/sh
  
set -x
  
sudo apt-get purge xroad-common
sudo apt-get autoremove
sudo rm -rf /etc/xroad
sudo rm -rf /usr/share/xroad
sudo rm -rf /var/lib/xroad
sudo rm -rf /var/log/xroad
sudo rm -rf /var/tmp/xroad
sudo apt-get purge nginx
sudo -u postgres dropdb messagelog
sudo -u postgres dropdb serverconf
sudo -u postgres psql -c "drop user serverconf"
sudo apt-get purge postgresql
```

2. I would recommend using public addresses although it should work if all the servers are in the same private network. Requirements for central server are listed in https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md chapter 2.3. Requirements for security server are listed in https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md chapter 2.3.

3. I would recommend using public addresses although it should work if all the servers are in the same private network.

**Comment by leviduran** [comment]
Hi @iluwatar ,from this question I have another although not directly related to IP/DNS config. When installing a security server the same prompt that ask for the IP and DNS info also lets you define a CN for that particular instance. We key in just the host name instead of the standard format for common names (country, organization, organizational unit). Is it posible to change it via configuration files and/or the security server web console without reinstalling?

**Comment by algmomizz** [comment]
Thanks @iluwatar . One last question, for us to be able to expose our x-road instances we rely on a DNS that's dynamically link to an IP, meaning the IP is not static it might change but the DNS will always point to the correct x-road instance. Does this represent a constraint when configuring the IP and DNS information at the installation prompt?

**Comment by iluwatar** [comment]
@leviduran the security server installer creates two separate self-signed certificates. The first is the one admin web UI uses and the second one is used for communication between security server and information systems. The second one is possible to change using the admin UI as described in https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#103-changing-the-internal-tls-key-and-certificate. The first one you need to change by replacing the files `/etc/xroad/ssl/nginx.cert` and `/etc/xroad/ssl/nginx.key`.

**Comment by iluwatar** [comment]
@algmomizz the short answer is that there is no problem in using dynamic DNS as long as you register the security servers with the DNS name and not the IP address. 

The addresses of the security servers are resolved from the global configuration generated by the central server. The global configuration is like an address book and if it contains DNS name for your security server everything should be fine. In case the IP address changes there may be some delay before the other security servers are able to resolve the new address (DNS TTL + Java cache time).

**Comment by leviduran** [comment]
OK got it @iluwatar thanks.

**Comment by algmomizz** [comment]
Excellent. I will then register the security servers with the DNS only. Thanks @iluwatar
