### ISSUE TITLE
Failed to send registration request

### ISSUE THREAD

**Issue by john-alstru** [ria-ee/X-Road#41]
I got another error message when sending a registration request
![1](https://cloud.githubusercontent.com/assets/12060643/25696099/6f33718a-30e8-11e7-8bef-a6af8db3ddd8.png)

I'm registering TEST client, the error message show me `subsystem-gitlab-1` client, why?
And what's the IS certificates?

**Comment by iluwatar** [comment]
It may be that you have configured management services to require TLS authentication. Verify that `Verify TLS certificate` is unchecked for management services authCertDeletion, clientReg and clientDeletion.

**Comment by john-alstru** [comment]
Yes,  that works.

Is it a must for management service to uncheck the 'Verify TLS certificate' option?

**Comment by iluwatar** [comment]
You can also configure it to verify the TLS certificate. In that case you need to take the central server's certificate from `/etc/xroad/ssl/internal.crt` and upload it to the management service provider security server's Internal TLS Certificates so the security server knows which certificate to trust.

**Comment by john-alstru** [comment]
Thank you.
