### ISSUE TITLE
Configuring  Central and Security Server for DNS instead of IP

### ISSUE THREAD

**Issue by algmomizz** [ria-ee/X-Road#45]
Hello. I'm currently configuring x-road cs (initialization when the web console is accessed for the first time) and I've hit a snag. When inputting the central server address the console won't let me key in an extended DNS path . For example if our main DNS is example.com and I want to input example.com/path1/cs the console will generate an error saying that it needs either a DNS or an IP address (it did allow me to input it in this way in the cs installation ). So I'm wondering if this is possible when configuring x-road. Everything that begins with example.com is directed through a CDN and then to out data center where the DNS paths are mapped to the corresponding internal IP addresses. Is it possible to configure x-road in this way?. Thanks in advance!

**Comment by iluwatar** [comment]
Unfortunately this is not possible. The central server address has to be simple DNS name or IP address without any path after it. You could use another mapping scheme like `cs1.example.com` if you need a workaround.

**Comment by algmomizz** [comment]
Thanks @iluwatar. We'll have to make some adjustments for the scheme as you suggested then.
